name: github actions test2

on: push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: pull docker img
        run: |
          sudo docker pull minsukjinoaa/ci-test-base:ubuntu20.04
          sudo docker save minsukjinoaa/ci-test-base:ubuntu20.04 | gzip >my-ci-test.tar.gz
          ls -la

      - name: upload image
        uses: actions/upload-artifact@v2
        with:
          name: my-ci-test.tar.gz
          path: my-ci-test.tar.gz

  job2:
    name: second job
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: download image
        uses: actions/download-artifact@v2


      - name: load image
        run: |
          pwd
          ls -la
          sudo docker load <my-ci-test.tar.gz
